# Generated by Django 3.1.1 on 2020-09-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
                ('player_jercy_number', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('player_history', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.CharField(max_length=100)),
                ('club_state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewards', models.IntegerField()),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_api.matches')),
            ],
        ),
        migrations.AddField(
            model_name='matches',
            name='players',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_api.player'),
        ),
    ]
