# Generated by Django 3.1.1 on 2020-09-13 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='players',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='teams',
        ),
        migrations.AddField(
            model_name='matches',
            name='teams_A',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='cricket_api.team'),
        ),
        migrations.AddField(
            model_name='matches',
            name='teams_B',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='cricket_api.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cricket_api.team'),
        ),
    ]
